name: Build MacOS SDK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OSXCross
        uses: actions/checkout@v4
        with:
          repository: tpoechtrager/osxcross

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libssl-dev lzma-dev libxml2-dev cpio

      - name: Download Pre-packaged MacOS SDK
        run: |
          # 既成の MacOSX15.sdk を取得してアーカイブ化
          mkdir -p tarball
          curl -L -o tarball/MacOSX15.0.sdk.tar.xz https://github.com/joseluisq/macosx-sdks/releases/download/15.0/MacOSX15.0.sdk.tar.xz

      - name: Upload SDK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-sdk
          path: "tarball/*.sdk.tar.xz"
